### ISSUE TITLE
mingw32: key "5F92EFC1A47D45A1" is unknown?

### ISSUE THREAD

**Issue by feifeilanniao** [Gator96100/ProxSpace#10]
![image](https://user-images.githubusercontent.com/16999626/47276308-af997980-d5e8-11e8-8f1e-1a05ca362221.png)
When i run the runme64.bat, some errors occur, what should i do to deal with these problem?

**Comment by Gator96100** [comment]
Those errors are to be expected when ProxSpace is run for the first time.
Are these errors appear after the first run?
Please make sure you did not download ProxSpace via git.

**Comment by feifeilanniao** [comment]
Errors appear appear after the fisrt run.
I download ProxSpace via chrome.
![image](https://user-images.githubusercontent.com/16999626/47291696-3117f880-d637-11e8-9dab-fb9ff725e479.png)

**Comment by Gator96100** [comment]
Run `pacman --force -Syuu` and try again.

**Comment by feifeilanniao** [comment]
![image](https://user-images.githubusercontent.com/16999626/47292093-94565a80-d638-11e8-986b-e0d7253c398b.png)

**Comment by Gator96100** [comment]
Try `pacman --force -Syuu`

**Comment by feifeilanniao** [comment]
Any different?
![image](https://user-images.githubusercontent.com/16999626/47292300-22324580-d639-11e8-934c-2cec66681c9b.png)

**Comment by Gator96100** [comment]
Github seems to have an inconsistency problem and I thought I forget the `--force` option.
Due to the current Github problem this error could be caused by a corrupted download, try redownloading ProxSpace.
Be sure to run ProxSpace as admin and that your firewall is not blocking connections.
What Windows version are you running?

**Comment by feifeilanniao** [comment]
Windows 10.
When i try to run runme64.bat as admin, it can't find the path.

**Comment by arslanbisharat** [comment]
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown

**Comment by Gator96100** [comment]
Make sure you are using the latest ProxSpace version. All ProxSpace version prior to v3.5 will no longer work as there was a keyring changes. See #41 #39
