### ISSUE TITLE
mingw ansi colors inside pm3 client

### ISSUE THREAD

**Issue by iceman1001** [Gator96100/ProxSpace#14]
One thing that has been on my mind is the strangeness with ansi colors in the mingw based proxspace environment.
Since there is color when we start the mingw env but once we start the proxmark3 client the output stops being able to translate the escape sequences correct.

Does someone have a solution for this?

**Comment by merlokk** [comment]
It the same for me. I dont know why.

**Comment by Gator96100** [comment]
It might have to do with readline6. Readline7 might work. I'll check it out.

**Comment by Gator96100** [comment]
Is there an existing command that should have a colored output?

**Comment by iceman1001** [comment]
you can modify  "showBanner" function in client/proxmark.c   (for RRG or iceman based repo)  It has colors

**Comment by Gator96100** [comment]
MinGW is a toolchain to compile on Windows natively with no POSIX emulation layer. That means if you want colored output, you need to do it the Windows way. Prior to Windows 10 there were no ansi sequences. The only way is:
```
SetConsoleTextAttribute( GetStdHandle(STD_OUTPUT_HANDLE), FOREGROUND_RED );
printf("Hello World!");
SetConsoleTextAttribute( GetStdHandle(STD_OUTPUT_HANDLE), 0x0f);
```
The reason why there is colored output when you start Proxspace is that the MinGW packages are compiled with msys2 as POSIX emulation layer. Here is a pretty good summery [MSYS2 Shell or MinGW-w64 Shell](https://sourceforge.net/p/msys2/discussion/general/thread/dcf8f4d3/#8473/588e)

There are some possibilities to enable colored output:

- Handle all coloring in the Proxmark source code, with the method described above
- Changing Proxspace from MinGW shell to msys2 shell, this comes at a performance
penalty
- Shipping ProxSpace with a different terminal

**Comment by iceman1001** [comment]
Does that setconsoletextattribute work?  I tried a somewhat similar techneque with enableing vt escapes but it didn't work.

**Comment by iceman1001** [comment]
and yes,  that did work,  to answer my own question.

**Comment by iceman1001** [comment]
mingw is compiled with msys2 and  proxmark3 client is compiled with mingw-toolchain (which doesn't have that ansi stuff)..  It makes more sense now.    However I have a hard time seeing the SetConsoleTextAttribute in a simple  **define** macro way like on linux/apple.

**Comment by Gator96100** [comment]
I tried to compile the Proxmark client with msys2 to see what would happen. The problem is that every Makefile and .c/.h file that differentiate between mingw and linux/macOS need to be changed as msys does set other variables that mingw does.  I might look into it again when I have more time available.

**Comment by iceman1001** [comment]
how about we drop this one?
