### ISSUE TITLE
Proxspace is 18Gb

### ISSUE THREAD

**Issue by iceman1001** [Gator96100/ProxSpace#15]
The current proxspace is 18gb,   without the pm3 repo.
That is massive.  We really need to make it smaller again.  Ppl with laptops has not that large disc always.

The libjansson can be removed again,  and the QT5 must be able to be smaller, I think its 10Gb.

@doegox maybe has some other suggestions.

**Comment by Gator96100** [comment]
I will see what I can do.
The libjansson does only take 65KB, but if it is no longer needed I'll remove it.
The pacman cache folder however does take up 4.2 GB if x86 and x64 dependencies are installed, this folder can be safely deleted after the first time installation.
QT5 does take a significant disk space, but there is nothing I can do about it. To make it smaller I would need to build and distribute my own QT5 packages. Maybe I can get rid of the QT5 examples (1.5GB).
With all of the above changes Proxspace for x86 would be 6.2GB, with only x64 dependencies 6.4GB and with x86 and x64 dependencies 11.5GB big.

**Comment by iceman1001** [comment]
well,  that is a start.

**Comment by micolous** [comment]
Maybe an option to build without QT5?  If I want to test that I haven't broken something on Windows, I normally don't care about the GUI features.

More generally, it may also be possible to build PM3 for Windows using mingw32/64 cross-compilers on Linux, but it would require some adjustment of the Makefiles: I opened https://github.com/Proxmark/proxmark3/issues/816 for this.

**Comment by Gator96100** [comment]
The Proxmark client will build just fine without QT5 and is usable, the GUI features are missing of cause.
However I will not remove QT5 from Proxspace.

**Comment by Gator96100** [comment]
Proxspace does now cleanup the pacman cache and removes qt5 example folder after install.
