### ISSUE TITLE
path and vars

### ISSUE THREAD

**Issue by iceman1001** [Gator96100/ProxSpace#19]
Two issues in one picture.
1.  that user path is not on my computer.  It looks like a path from @Gator96100 
2. the PATH var isnt correctly ended?

![image](https://user-images.githubusercontent.com/8577004/63769389-fc1da780-c8d2-11e9-90f8-6e42ae50e96a.png)

**Comment by iceman1001** [comment]
pkg-config tells a story of julius the user...

![image](https://user-images.githubusercontent.com/8577004/63771758-0e4e1480-c8d8-11e9-8267-d9e851ee1e5e.png)

**Comment by Gator96100** [comment]
That is interesting. I did test it in a VM with a different user and it did work. I will look into it. Maybe it is a better idea to have the packages downloaded in cache and install it when ProxSpace is first run. 

Only QT seems to be affected, that makes sense as QT does some file patching during install.

**Comment by iceman1001** [comment]
could be.

**Comment by Gator96100** [comment]
I did upload a new version. Now the packages are only in cache and will be installed automatically. After the installation the cache will be cleared. Could you please try again and check if this error still occurs?
