### ISSUE TITLE
ProxSpace and GIT installed

### ISSUE THREAD

**Issue by sherhannn79** [Gator96100/ProxSpace#21]
I have a git installed with default settings. 
1. I downloaded ProxSpace v3.2 release ProxSpace-64.7z
2. I run runme64.bat.
3. After the ProxSpace has downloaded all the updates, I run runme64.bat again and I get the following:
![proxspace](https://user-images.githubusercontent.com/54765500/65821667-30251900-e241-11e9-8915-7a267dcf11b6.jpg)

**Comment by Gator96100** [comment]
Have a look at [http://proxmark.org/forum/viewtopic.php?id=6573](url)
Did you extract ProxSpace to a location without spaces?

**Comment by sherhannn79** [comment]
In the names of the paths I have no spaces, except that the hyphen in the 'ProxSpace-64'. I'll try to remove the hyphen and reinstall.

**Comment by sherhannn79** [comment]
After removing the hyphen and reinstalling, the problem is resolved. Thank!
