### ISSUE TITLE
Problem about building the fpga_lf.bit and fpga_hf.bit

### ISSUE THREAD

**Issue by feifeilanniao** [Gator96100/ProxSpace#26]
**Describe the bug**
I'd like to build the fpga_lf.bit and fpga_hf.bit by myself, but it seem that some pack missing.
**To Reproduce**
1.git clone 'https://github.com/RfidResearchGroup/proxmark3.git' to '/pm3'
2. Go to 'proxmark3-master/fpga'
3. Execute 'make'

**Screenshots**
![image](https://user-images.githubusercontent.com/16999626/70960619-7f4d4e00-20ba-11ea-9223-9dd26051872d.png)

**Comment by feifeilanniao** [comment]
i just want to refresh the image, i try to the 'make clean && make all',and flash the 'fullimage.elf' into the device, after the 'hw version' command, some messages show that nothing change to the image, due to nothing change to the fpga_lf.bit and fpga_hf.bit?

messages return after ‘hw version’ command like below
     "LF image built for 2s30vq100 on 2019-07-31 at 15:57:16",
    " HF image built for 2s30vq100 on 2018-09-03 at 21:40:23"

**Comment by iceman1001** [comment]
you will need to use the xilinik buildchain in order to compile fpga part.  This isn't inside the Proxspace env.

**Comment by feifeilanniao** [comment]
ise webpack? i have a try. thank you @iceman1001

**Comment by Gator96100** [comment]
I did look into including it with Proxspace, however the Xilinx ISE WebPACK does not allow redistribution.
