### ISSUE TITLE
32 bit msys2 and libsndfile error

### ISSUE THREAD

**Issue by merlokk** [Gator96100/ProxSpace#27]
sometimes if you using msys2 in 32 bit mode - it needs to add this 
`pacman -S mingw-w64-i686-libsndfile`

**Comment by Gator96100** [comment]
Are you using the latest release? It was added, see a2899a4a9c0c0f28fccfc227c70ab97cb8453762

**Comment by merlokk** [comment]
`mingw-w64-x86_64-libsndfile` - looks like it 64 it only

**Comment by Gator96100** [comment]
`mingw-w64-x86_64-libsndfile` for 64 bit and `mingw-w64-i686-libsndfile` for 32 bit.

**Comment by merlokk** [comment]
yes, sorry. its ok)
