### ISSUE TITLE
autobuild.sh

### ISSUE THREAD

**Issue by Windslab** [Gator96100/ProxSpace#31]
Please replace it to fix an errors with builds:
[autobuild.sh.zip](https://github.com/Gator96100/ProxSpace/files/4257963/autobuild.sh.zip)

**Comment by Gator96100** [comment]
Don't worry, I will fix it, I simply did not have time yet. I will probably fix it this weekend as well as create a new release.

**Comment by Gator96100** [comment]
Should be fixed now, a release will follow
