### ISSUE TITLE
outdated mirrorlist

### ISSUE THREAD

**Issue by mrseeker** [Gator96100/ProxSpace#33]
I am having issues getting the installer to run, most likely because the mirrorlist is outdated. It keeps referring to repo.msys2.org which is incorrect, the new one is packages.msys2.org.

https://github.com/Gator96100/ProxSpace/blob/c438a118bf384d8ef3b811492411937e5f2c6b43/msys2/etc/pacman.d/mirrorlist.msys#L7

**Comment by Gator96100** [comment]
The mirrorlist is correct. repo.msys2.org just has problems at the moment. packages.msys2.org has no binary packages.
