### ISSUE TITLE
Installing ProxSpace for Proxmark3 to Windows 10

### ISSUE THREAD

**Issue by Windslab** [Gator96100/ProxSpace#36]
I happy to tell you that is community now have easy access to video guide for installing ProxSpace to Windows. You can use it as video instruction at your title page.

https://youtu.be/EfSgw40w4pc

Many Thanks

**Comment by Gator96100** [comment]
The git installation is not required nor recommended. ProxSpace ships with git. 
It is recommended to use the latest release rather than the latest master as it speeds up the package download. 

The installation instruction in the README should be easy enough to follow.
