### ISSUE TITLE
Err with pgp keys

### ISSUE THREAD

**Issue by Windslab** [Gator96100/ProxSpace#41]
![image](https://user-images.githubusercontent.com/60715874/89879359-80903580-dbcb-11ea-8601-0de425374e21.png)

**Comment by Gator96100** [comment]
I need a little more information.
Please post the full output.
Are you running the latest ProxSpace version?

**Comment by Windslab** [comment]
> I need a little more information.
> Please post the full output.
> Are you running the latest ProxSpace version?

That's full.
ps-repiar and all of the ps-* does't work, with the same err.
I think something with a date, that's similar to 5 month Proxspace as it's has installed.
How do I can clear the all chache?

**Comment by Gator96100** [comment]
All ProxSpace version prior to v3.5 will no longer work as there was a keyring changes.

**Comment by Windslab** [comment]
So do I need reinstall it?

**Comment by Gator96100** [comment]
You need to download the latest version and install it again.

**Comment by Windslab** [comment]
Many Thanks,
You can do your product better next time, by releasing new! :)

вт, 11 авг. 2020 г. в 13:20, Gator96100 <notifications@github.com>:

**Comment by Gator96100** [comment]
Maybe next time you verify if it is still an issue before creating one.
