### ISSUE TITLE
Most of the links are for Chinese sites

### ISSUE THREAD

**Issue by biobar** [Gator96100/ProxSpace#45]
Hi
Ran this earlier and was wondering why it’s pulling files from Chinese domains(.cn). Why is that?

**Comment by Gator96100** [comment]
During the initial setup it will rank the download mirrors, so you download from the fastest one. In your case, the fastest download mirror was from a Chinese server. 
If you wish to restore the original msys2 ranking you can run following commands:
```
mv /etc/pacman.d/mirrorlist.mingw64.backup /etc/pacman.d/mirrorlist.mingw64
mv /etc/pacman.d/mirrorlist.msys.backup /etc/pacman.d/mirrorlist.msys
```
Keep in mind all mirrors are official msys2 mirrors.
