### ISSUE TITLE
Uninstalled the usb driver 

### ISSUE THREAD

**Issue by SnickerZ123** [Gator96100/ProxSpace#48]
I uninstalled the usb driver as I couldn't find the device and it was in the hidden section.
I can no longer find it at all, how do I get it back?

**Comment by Gator96100** [comment]
What Windows version do you use?

On Windows 10 the driver will be installed automatically. If you uninstall the driver unplugging the pm3 and plugging it back in will reinstall the driver. Sometimes using a different usb port will also cause the driver to be reinstalled.

For older Windows versions you have to manually install the driver, which can be found in the repo you are using.

**Comment by SnickerZ123** [comment]
done thanks

**Comment by SnickerZ123** [comment]
hey, any chance you could show me how this works?
I'd pay you to teach me, I've encountered some errors and I can't find anything to fix them

**Comment by Gator96100** [comment]
I don’t offer paid support. I recommend you join the Discord server, where you can get a lot of help https://discord.gg/QfPvGFRQxH

If you are not happy with the community support, @iceman1001 does offer paid support at patreon: https://www.patreon.com/bePatron?u=16606719
