### ISSUE TITLE
Dumps go to working directory, dispite `prefs set savepaths`

### ISSUE THREAD

**Issue by non-bin** [Gator96100/ProxSpace#49]
I can't get `prefs set savepaths` to work, I've tried:
 - the `-c` option
 - C:\path\ProxSpace\pm3\saves
 - \path\ProxSpace\pm3\saves
 - C:\path\ProxSpace\pm3/saves
 - C:\\path\\ProxSpace\\pm3/saves
 - C:\\path\\ProxSpace\\pm3\\saves

But files always seem to end up wherever I run the pm3 script from. I might add a line to the script to cd to the saves directory as a temporary fix

**Comment by Gator96100** [comment]
That's not a ProxSpace bug. `prefs set savepaths` is not properly implemented in the client. I suggest to create an issue at [RfidResearchGroup/proxmark3](https://github.com/RfidResearchGroup/proxmark3)

**Comment by non-bin** [comment]
Thanks, I will
