### ISSUE TITLE
mingw gcc broken on Windows 7 (x86_32)

### ISSUE THREAD

**Issue by micolous** [Gator96100/ProxSpace#6]
Out of the box, `gcc` won't run on Windows 7 (x86_32), and it complains that `libwinpthread-1.dll` is not compatible with that version of Windows.

I was able to resolve this by copying `msys/mingw/i686-w64-mingw32/lib/libwinpthread-1.dll` to `msys/mingw/bin/`, and overwriting it.

**Comment by Gator96100** [comment]
Fixed with the new msys2 update
